import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookieBanner from "@/components/tracking/CookieBanner";
import AnalyticsGate from "@/components/tracking/AnalyticsGate";

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}

        <AnalyticsGate
          googleAnalyticsId={profile.google_analytics_id}
          facebookPixelId={profile.facebook_pixel_id}
          tiktokPixelId={profile.tiktok_pixel_id}
          hubspotPortalId={profile.hubspot_portal_id}
          hubspotEnabled={profile.hubspot_tracking_enabled}
          isPreview={isPreview}
        />
      </body>
    </html>
  );
}




// Template CSS (loaded once)
import "./templates/tech-clean.css";
import "./templates/dj-dark.css";
import "./templates/dancer-light.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`app-root ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
         <CookieBanner />
      </body>
    </html>
  );
}
